DECLARE				
  @DATEST AS VARCHAR(10) = '2013-10-01',				
  @DATEEN AS VARCHAR(10) = '2013-11-15',
  @SalaType AS VARCHAR(2) = 'Y7',
  @WF_Status AS VARCHAR(1) = '8';
SELECT T.EMPLOYEEID, LV , DATEID , HOUR_D , OT5 , OT1, OT2, OT3 
  , CASE WHEN HOUR_D < 0 THEN 'HOUR_D'
        WHEN OT5 < 0 THEN 'OT 0.5 à·èÒ'
        WHEN OT1 < 0 THEN 'OT 1 à·èÒ'
        WHEN OT2 < 0 THEN 'OT 2 à·èÒ'
        WHEN OT3 < 0 THEN 'OT 3 à·èÒ'
    END CheckErr
FROM TTIME_CURRENT T
WHERE CONVERT(DATE,T.DATEID) BETWEEN @DATEST AND @DATEEN
AND T.BU1 != '100'
AND T.SALATYPE != @SalaType --EXCLUDE TRAINEE, ALL
AND T.WF_STATUS = @WF_Status -- AC APPROVE, ALL
AND CASE WHEN HOUR_D < 0 THEN '1'
        WHEN OT5 < 0 THEN '1'
        WHEN OT1 < 0 THEN '1'
        WHEN OT2 < 0 THEN '1'
        WHEN OT3 < 0 THEN '1'
    END IS NOT NULL
ORDER BY EMPLOYEEID , DATEID;