package mapping;

// Generated 4 ¸.¤. 2552, 15:49:53 by Hibernate Tools 3.2.4.GA

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Long id;
	private String chvTitle;
	private String chvDes;

	public Book() {
	}

	public Book(String chvTitle, String chvDes) {
		this.chvTitle = chvTitle;
		this.chvDes = chvDes;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getChvTitle() {
		return this.chvTitle;
	}

	public void setChvTitle(String chvTitle) {
		this.chvTitle = chvTitle;
	}

	public String getChvDes() {
		return this.chvDes;
	}

	public void setChvDes(String chvDes) {
		this.chvDes = chvDes;
	}

}
